/*
 * Promitea REST API v2
 * Promitea REST API v2
 *
 * OpenAPI spec version: 2.0
 * Contact: support@apitea.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.promitea.client.api;

import com.google.gson.reflect.TypeToken;
import com.promitea.client.ApiCallback;
import com.promitea.client.ApiClient;
import com.promitea.client.ApiException;
import com.promitea.client.ApiResponse;
import com.promitea.client.Configuration;
import com.promitea.client.HasApiClient;
import com.promitea.client.Pair;
import com.promitea.client.ProgressRequestBody;
import com.promitea.client.ProgressResponseBody;
import com.promitea.client.model.Organization;

import java.io.IOException;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RegistrationRestControllerApi implements HasApiClient
{
    private ApiClient apiClient;

    public RegistrationRestControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RegistrationRestControllerApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for registerOrganizationUsingPOST
     * @param organizationModel Organization object that needs to be added (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call registerOrganizationUsingPOSTCall(Organization organizationModel, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException
    {
        Object localVarPostBody = organizationModel;

        // create path and map variables
        String localVarPath = "/register";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "Authorization-Key" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call registerOrganizationUsingPOSTValidateBeforeCall(Organization organizationModel, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'organizationModel' is set
        if (organizationModel == null) {
            throw new ApiException("Missing the required parameter 'organizationModel' when calling registerOrganizationUsingPOST(Async)");
        }
        

        com.squareup.okhttp.Call call = registerOrganizationUsingPOSTCall(organizationModel, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Register a new organisation into Promitea
     * Returns organisation detail
     * @param organizationModel Organization object that needs to be added (required)
     * @return Organization
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Organization registerOrganizationUsingPOST(Organization organizationModel) throws ApiException {
        ApiResponse<Organization> resp = registerOrganizationUsingPOSTWithHttpInfo(organizationModel);
        return resp.getData();
    }

    /**
     * Register a new organisation into Promitea
     * Returns organisation detail
     * @param organizationModel Organization object that needs to be added (required)
     * @return ApiResponse&lt;Organization&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Organization> registerOrganizationUsingPOSTWithHttpInfo(Organization organizationModel) throws ApiException {
        com.squareup.okhttp.Call call = registerOrganizationUsingPOSTValidateBeforeCall(organizationModel, null, null);
        Type localVarReturnType = new TypeToken<Organization>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Register a new organisation into Promitea (asynchronously)
     * Returns organisation detail
     * @param organizationModel Organization object that needs to be added (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call registerOrganizationUsingPOSTAsync(Organization organizationModel, final ApiCallback<Organization> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = registerOrganizationUsingPOSTValidateBeforeCall(organizationModel, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Organization>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
