/*
 * Promitea REST API v2
 * Promitea REST API v2
 *
 * OpenAPI spec version: 2.0
 * Contact: support@apitea.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Document;
import io.swagger.client.model.Item;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Project phase entity
 */
@ApiModel(description = "Project phase entity")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-05T07:13:22.864Z")
public class Phase {
  @SerializedName("code")
  private String code = null;

  @SerializedName("documents")
  private List<Document> documents = null;

  @SerializedName("items")
  private List<Item> items = null;

  @SerializedName("phaseId")
  private String phaseId = null;

  public Phase code(String code) {
    this.code = code;
    return this;
  }

   /**
   * phase type
   * @return code
  **/
  @ApiModelProperty(value = "phase type")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Phase documents(List<Document> documents) {
    this.documents = documents;
    return this;
  }

  public Phase addDocumentsItem(Document documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<Document>();
    }
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * phase documents
   * @return documents
  **/
  @ApiModelProperty(value = "phase documents")
  public List<Document> getDocuments() {
    return documents;
  }

  public void setDocuments(List<Document> documents) {
    this.documents = documents;
  }

  public Phase items(List<Item> items) {
    this.items = items;
    return this;
  }

  public Phase addItemsItem(Item itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<Item>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * phase items
   * @return items
  **/
  @ApiModelProperty(value = "phase items")
  public List<Item> getItems() {
    return items;
  }

  public void setItems(List<Item> items) {
    this.items = items;
  }

  public Phase phaseId(String phaseId) {
    this.phaseId = phaseId;
    return this;
  }

   /**
   * phase id
   * @return phaseId
  **/
  @ApiModelProperty(value = "phase id")
  public String getPhaseId() {
    return phaseId;
  }

  public void setPhaseId(String phaseId) {
    this.phaseId = phaseId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Phase phase = (Phase) o;
    return Objects.equals(this.code, phase.code) &&
        Objects.equals(this.documents, phase.documents) &&
        Objects.equals(this.items, phase.items) &&
        Objects.equals(this.phaseId, phase.phaseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, documents, items, phaseId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Phase {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    phaseId: ").append(toIndentedString(phaseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

