/*
 * Promitea REST API v2
 * Promitea REST API v2
 *
 * OpenAPI spec version: 2.0
 * Contact: support@apitea.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Text;
import io.swagger.client.model.User;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * A basic info project entity
 */
@ApiModel(description = "A basic info project entity")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-05T07:13:22.864Z")
public class ProjectBasicInfo {
  @SerializedName("additionalNames")
  private List<Text> additionalNames = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("manager")
  private User manager = null;

  @SerializedName("name")
  private Text name = null;

  public ProjectBasicInfo additionalNames(List<Text> additionalNames) {
    this.additionalNames = additionalNames;
    return this;
  }

  public ProjectBasicInfo addAdditionalNamesItem(Text additionalNamesItem) {
    if (this.additionalNames == null) {
      this.additionalNames = new ArrayList<Text>();
    }
    this.additionalNames.add(additionalNamesItem);
    return this;
  }

   /**
   * additional project names
   * @return additionalNames
  **/
  @ApiModelProperty(value = "additional project names")
  public List<Text> getAdditionalNames() {
    return additionalNames;
  }

  public void setAdditionalNames(List<Text> additionalNames) {
    this.additionalNames = additionalNames;
  }

  public ProjectBasicInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * project id
   * @return id
  **/
  @ApiModelProperty(value = "project id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ProjectBasicInfo manager(User manager) {
    this.manager = manager;
    return this;
  }

   /**
   * manager
   * @return manager
  **/
  @ApiModelProperty(value = "manager")
  public User getManager() {
    return manager;
  }

  public void setManager(User manager) {
    this.manager = manager;
  }

  public ProjectBasicInfo name(Text name) {
    this.name = name;
    return this;
  }

   /**
   * project name
   * @return name
  **/
  @ApiModelProperty(value = "project name")
  public Text getName() {
    return name;
  }

  public void setName(Text name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectBasicInfo projectBasicInfo = (ProjectBasicInfo) o;
    return Objects.equals(this.additionalNames, projectBasicInfo.additionalNames) &&
        Objects.equals(this.id, projectBasicInfo.id) &&
        Objects.equals(this.manager, projectBasicInfo.manager) &&
        Objects.equals(this.name, projectBasicInfo.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalNames, id, manager, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectBasicInfo {\n");
    
    sb.append("    additionalNames: ").append(toIndentedString(additionalNames)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    manager: ").append(toIndentedString(manager)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

